# Generated by Django 3.0.7 on 2020-06-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='author',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='title',
            new_name='name',
        ),
    ]
