# Generated by Django 3.0.7 on 2020-06-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200617_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='branch',
            field=models.CharField(choices=[('mechanical', 'Mechanical'), ('cs', 'Computer Science'), ('electrical', 'Electrical')], max_length=100),
        ),
    ]
