# Generated by Django 3.0.2 on 2020-07-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200617_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
